/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbonnementRouteImport } from './routes/abonnement'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BoutiquesRouteImport } from './routes/boutiques'
import { Route as CompteRouteImport } from './routes/compte'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PaiementRouteImport } from './routes/paiement'
import { Route as AdminBoutiquesRouteImport } from './routes/admin/boutiques'
import { Route as AdminUnlockRouteImport } from './routes/admin/unlock'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbonnementRoute = AbonnementRouteImport.update({
  id: '/abonnement',
  path: '/abonnement',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiquesRoute = BoutiquesRouteImport.update({
  id: '/boutiques',
  path: '/boutiques',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteRoute = CompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementRoute = PaiementRouteImport.update({
  id: '/paiement',
  path: '/paiement',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBoutiquesRoute = AdminBoutiquesRouteImport.update({
  id: '/admin/boutiques',
  path: '/admin/boutiques',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUnlockRoute = AdminUnlockRouteImport.update({
  id: '/admin/unlock',
  path: '/admin/unlock',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abonnement': typeof AbonnementRoute
  '/auth': typeof AuthRoute
  '/boutiques': typeof BoutiquesRoute
  '/compte': typeof CompteRoute
  '/contact': typeof ContactRoute
  '/paiement': typeof PaiementRoute
  '/admin/boutiques': typeof AdminBoutiquesRoute
  '/admin/unlock': typeof AdminUnlockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abonnement': typeof AbonnementRoute
  '/auth': typeof AuthRoute
  '/boutiques': typeof BoutiquesRoute
  '/compte': typeof CompteRoute
  '/contact': typeof ContactRoute
  '/paiement': typeof PaiementRoute
  '/admin/boutiques': typeof AdminBoutiquesRoute
  '/admin/unlock': typeof AdminUnlockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abonnement': typeof AbonnementRoute
  '/auth': typeof AuthRoute
  '/boutiques': typeof BoutiquesRoute
  '/compte': typeof CompteRoute
  '/contact': typeof ContactRoute
  '/paiement': typeof PaiementRoute
  '/admin/boutiques': typeof AdminBoutiquesRoute
  '/admin/unlock': typeof AdminUnlockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abonnement'
    | '/auth'
    | '/boutiques'
    | '/compte'
    | '/contact'
    | '/paiement'
    | '/admin/boutiques'
    | '/admin/unlock'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abonnement'
    | '/auth'
    | '/boutiques'
    | '/compte'
    | '/contact'
    | '/paiement'
    | '/admin/boutiques'
    | '/admin/unlock'
  id:
    | '__root__'
    | '/'
    | '/abonnement'
    | '/auth'
    | '/boutiques'
    | '/compte'
    | '/contact'
    | '/paiement'
    | '/admin/boutiques'
    | '/admin/unlock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbonnementRoute: typeof AbonnementRoute
  AuthRoute: typeof AuthRoute
  BoutiquesRoute: typeof BoutiquesRoute
  CompteRoute: typeof CompteRoute
  ContactRoute: typeof ContactRoute
  PaiementRoute: typeof PaiementRoute
  AdminBoutiquesRoute: typeof AdminBoutiquesRoute
  AdminUnlockRoute: typeof AdminUnlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abonnement': {
      id: '/abonnement'
      path: '/abonnement'
      fullPath: '/abonnement'
      preLoaderRoute: typeof AbonnementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutiques': {
      id: '/boutiques'
      path: '/boutiques'
      fullPath: '/boutiques'
      preLoaderRoute: typeof BoutiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte': {
      id: '/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof CompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiement': {
      id: '/paiement'
      path: '/paiement'
      fullPath: '/paiement'
      preLoaderRoute: typeof PaiementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/boutiques': {
      id: '/admin/boutiques'
      path: '/admin/boutiques'
      fullPath: '/admin/boutiques'
      preLoaderRoute: typeof AdminBoutiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/unlock': {
      id: '/admin/unlock'
      path: '/admin/unlock'
      fullPath: '/admin/unlock'
      preLoaderRoute: typeof AdminUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbonnementRoute: AbonnementRoute,
  AuthRoute: AuthRoute,
  BoutiquesRoute: BoutiquesRoute,
  CompteRoute: CompteRoute,
  ContactRoute: ContactRoute,
  PaiementRoute: PaiementRoute,
  AdminBoutiquesRoute: AdminBoutiquesRoute,
  AdminUnlockRoute: AdminUnlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
